version: "3.8"
services:
  app:
    hostname: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: builder
    command: air
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: .gcloud/credentials.json
    env_file:
      - .env
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"

